name = "GALAHAD"
uuid = "c591611e-c43e-4808-98fb-ce4cafe3a717"
authors = ["Alexis Montoison <alexis.montoison@polymtl.ca>", "Dominique Orban <dominique.orban@polymtl.ca>"]
version = "0.5.0"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
GALAHAD_jll = "1621ace8-c1f0-5e32-a05d-ca786afa56c2"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OpenBLAS32_jll = "656ef2d0-ae68-5445-9ca0-591084a874a2"
Quadmath = "be4d8f0f-7fa4-5f49-b795-2f01399ab2dd"

[weakdeps]
CUTEst = "1b53aba6-35b6-5f92-a507-53c67d53f819"

[extensions]
GALAHADCUTEstExt = "CUTEst"

[compat]
Accessors = "0.1.42"
CUTEst = "1.3.2"
GALAHAD_jll = "=5.3.0"
Quadmath = "0.5.10"
julia = "1.9"

[extras]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Printf"]
