name = "GALAHAD"
uuid = "c591611e-c43e-4808-98fb-ce4cafe3a717"
authors = ["Alexis Montoison <alexis.montoison@polymtl.ca>", "Dominique Orban <dominique.orban@polymtl.ca"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[targets]
test = ["Test", "Printf"]
